services:
  webserv:
    container_name: webserv
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./site:/var/www/html
    build: .
    environment:
      UID: ${MY_UID}
      GID: ${MY_GID}
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app/
        - action: rebuild
          path: ./Makefile
          target: /app/
        - action: sync+restart
          path: ./default.conf
          target: /app/default.conf
