services:
  webserv:
    container_name: webserv-${BUILD_TYPE}
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./site:/var/www/html/test_site
      - ./html-website-templates:/var/www/html/static_templates
      - ./src/:/app/src/
      - ./default.conf:/app/default.conf
      - ./Makefile:/app/Makefile
    build:
      context: .
      args:
        BUILD_TYPE: ${BUILD_TYPE}
    environment:
      UID: ${MY_UID}
      GID: ${MY_GID}
      BUILD_TYPE: ${BUILD_TYPE}
    restart: unless-stopped
    networks:
      - web-siege-network

  webserv-dev:
    container_name: webserv-dev
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./site:/var/www/html/test_site
      - ./html-website-templates:/var/www/html/static_templates
      - ./src/:/app/src/
      - ./default.conf:/app/default.conf
      - ./Makefile:/app/Makefile
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        BUILD_TYPE: ${BUILD_TYPE}
    environment:
      UID: ${MY_UID}
      GID: ${MY_GID}
      BUILD_TYPE: ${BUILD_TYPE}

  nginx:
    container_name: nginx
    ports:
      - "${NGINX_PORT_1}:8080"
      - "${NGINX_PORT_2}:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./site:/var/www/html/test_site
      - ./html-website-templates:/var/www/html/static_templates
    build:
      context: nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - nginx-siege-network

  siege:
    container_name: siege
    build:
      context: .
      dockerfile: Dockerfile.siege
    environment:
      CONTAINER: ${CONTAINER}
      PORT: ${PORT}
    volumes:
      - ./siege_test.sh:/app/siege_test.sh
      - ./siege.log:/app/siege.log
    networks:
      - web-siege-network
      - nginx-siege-network

networks:
  web-siege-network:
  nginx-siege-network:
