services:
  webserv:
    container_name: webserv-${BUILD_TYPE}
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./site:/var/www/html
      - ./src/:/app/src/
      - ./default.conf:/app/default.conf
      - ./Makefile:/app/Makefile
    build:
      context: .
      args:
        BUILD_TYPE: ${BUILD_TYPE}
    environment:
      UID: ${MY_UID}
      GID: ${MY_GID}
      BUILD_TYPE: ${BUILD_TYPE}
    restart: unless-stopped
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: ./src
    #       target: /app/
    #     - action: rebuild
    #       path: ./Makefile
    #       target: /app/
    #     - action: rebuild
    #       path: ./Dockerfile
    #     - action: sync+restart
    #       path: ./default.conf
    #       target: /app/default.conf
