FROM debian:bullseye-slim
RUN apt-get update
RUN apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_20.x -o nodesource_setup.sh && bash nodesource_setup.sh
RUN apt-get install -y make clang python3 php-cgi libpthread-stubs0-dev nodejs valgrind

RUN apt-get install -y git

RUN git clone --depth=1 https://github.com/unkn0wn107/website-examples.git /var/www/

RUN mkdir -p /var/www/html

WORKDIR /app

COPY --chmod=755 ./build.sh .

ENTRYPOINT [ "./build.sh" ]
CMD ["tail", "-f", "/dev/null"]
