FROM debian:bookworm-slim
RUN apt-get update
RUN apt-get install -y curl
RUN apt-get install -y make clang python3 php-cgi libpthread-stubs0-dev nodejs valgrind

RUN apt-get install -y git

RUN git clone --depth=1 https://github.com/unkn0wn107/website-examples.git /var/www/

RUN mkdir -p /var/www/html

WORKDIR /app

COPY --chmod=755 ./run.sh .

ENTRYPOINT [ "./run.sh" ]
CMD ["tail", "-f", "/dev/null"]
